apiVersion: v1
kind: PersistentVolume
metadata:
   name: hostpathpv
spec: 
   storageClassName: manual
   capacity: 
     storage: 1Gi
   accesMOdes:
   -ReadWriteOnce
   nfs: 
      server: nfs server private ip
	  path: "/mnt/share/"
