apiVersion: v1
kind: ReplicationController
metadata:
   name: javawebapprc
spec:
 replicas: 2
 selector:  
   app: javawebapp
 template:
   metadata:
     name: javawebapppod
     labels:
       app: javawebapp
   spec:
     containers:     
     - name: javawebappcontainer
       image: dockerhandson/java-web-app
       ports:
       - containerPort: 8080        
      

